# Generated by Django 5.2.7 on 2026-02-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("INCOME", "Entrada"),
                    ("EXPENSE", "Saída"),
                    ("CREDITO", "Crédito"),
                    ("DEBITO", "Débito"),
                    ("PIX", "PIX"),
                ],
                max_length=7,
                verbose_name="Tipo",
            ),
        ),
    ]
